application: travelblog-fun
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /.*
  script: blogmain.app

libraries:
- name: jinja2
  version: latest